### ISSUE TITLE
Make the tests self-contained

### ISSUE THREAD

**Issue by goloroden** [sealsystems/node-http-server#2]
Hi there 😊 

Right now, the tests are not self-contained, as you manually need to start Consul that the tests can connect to.

It would be great if starting and stopping an appropriate Consul server with the correct setup could be done automatically by the tests.

**Comment by seal-mis** [comment]
Thank you very much for your suggestion! 😃

In the next couple of weeks, we have to update our build configuration for CircleCI. This will be the perfect opportunity to also rework the test setup.

I created an internal issue and close this one to prevent duplicates.
