### ISSUE TITLE
Fix tests for macOS

### ISSUE THREAD

**Issue by goloroden** [sealsystems/node-http-server#3]
Hey there 😊 

Some of the tests (to be exactly, it's the ones that rely on Consul for getting the external IP) don't work on macOS. I have tracked it down to the following:

- The tests try to obtain the system's external IP from Consul.
- What they get as a result is the IP of the Docker container of Consul.
- Then they try to run a server on this IP, which fails.

After having discussed this with @seal-mis, we have come to the guess that this works on Linux, but not on macOS (for whatever reason). As I don't have a Linux at hand, I can't reproduce this on Linux, but this may be a good starting point…

**Comment by seal-mis** [comment]
It turned out to be a incompatibility with the current version of Consul which has been fixed in #1.
